name: build-docker-image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure ACR Login
        run: az acr login -n ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}
      - name: Release Build
        if: github.event_name == 'release'
        run: |
          cd Projects/Project_5/api_code/ &&
          make build &&
          docker tag docker-web:latest \
            ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/oc-nlp-web:${{ github.event.release.tag_name }} &&
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/oc-nlp-web:${{ github.event.release.tag_name }}
      - name: Test Build
        if: github.event_name != 'release'
        run: |
          cd Projects/Project_5/api_code/ &&
          make build &&
          docker tag docker-web:latest \
            ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/oc-nlp-web:dev&&
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/oc-nlp-web:dev
