name: deploy-to-azure

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure ACR Login
        run: az acr login -n ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}
      - name: Release Deploy
        if: github.event_name == 'release'
        run: |
          az webapp config container set -g oc-learning -n ${{ secrets.AZURE_APP_SERVICE_NAME }} \
            --docker-custom-image-name shopifyappsregistry.azurecr.io/oc-nlp-web:${{ github.event.release.tag_name }} &&
      - name: Test Deploy
        if: github.event_name != 'release'
        run: |
          az webapp config container set -g oc-learning -n ${{ secrets.AZURE_APP_SERVICE_NAME }} \
            --docker-custom-image-name shopifyappsregistry.azurecr.io/oc-nlp-web:dev &&
