name: dev-cd-pipeline

on:
  push:
    branches:
      - projects

jobs:
  dev-cd-pipeline:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Build Docker Image
        uses: ./.github/workflows/build-docker-image.yml
        with:
          image-tag: dev
        secrets: inherit
      - name: Deploy to Azure
        uses: ./.github/workflows/deploy-to-azure.yml
        with:
          image-tag: dev
        secrets: inherit
