name: prod-cd-pipeline

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image-tag: prod
      environment: prod
    secrets: inherit
  test-docker-image:
    needs: [build-docker-image]
    uses: ./.github/workflows/test-docker-image.yml
    with:
      image-tag: prod
      environment: prod
    secrets: inherit
  deploy-to-azure:
    needs: [test-docker-image]
    uses: ./.github/workflows/deploy-to-azure.yml
    with:
      image-tag: prod
      environment: prod
    secrets: inherit
